### ISSUE TITLE
WXSS 文件编译错误

### ISSUE THREAD

**Issue by bostin** [icebreaker-template/weapp-vite-tailwindcss-template#1]
[ WXSS 文件编译错误] 
./app.wxss(276:19): error at token `:`(env: macOS,mp,1.06.2409131; lib: 3.6.1)

**Comment by bostin** [comment]
已定位，是daisyui的问题，不兼容

**Comment by sonofmagic** [comment]
是的 daisyui 里面有些 css 小程序兼容不了，这点用 weapp-tailwindcss 转译也没有用，因为原生小程序就说不支持的
